// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'c4f4694cc346d88bd5c89dbb8315be20399bb6efa153683dd53dd96f7785b6b9'>;
export type ExecutionHash =
  ExecutionHashBase<'aef44aafeb4263f4cf2552c32efde12b3f101b33bc2c0acf6e5281a31e90f6c8'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly JournalEntry: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly source: 'GOODS_RECEIVED' | 'SALE' | 'SALE_COST' | 'DAY_CLOSED' | 'SUPPLIER_PAYMENT';
      readonly reference: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly storeCode: CodecTypes['pg/text@1']['output'] | null;
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly JournalLine: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly journalEntryId: CodecTypes['pg/text@1']['output'];
      readonly accountCode: CodecTypes['pg/text@1']['output'];
      readonly debitCents: CodecTypes['pg/int4@1']['output'];
      readonly creditCents: CodecTypes['pg/int4@1']['output'];
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ProcessedEvent: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly PurchaseCommitment: {
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['output'];
      readonly supplierId: CodecTypes['pg/text@1']['output'];
      readonly supplierName: CodecTypes['pg/text@1']['output'];
      readonly paymentTerms: CodecTypes['pg/text@1']['output'];
      readonly totalCents: CodecTypes['pg/int4@1']['output'];
      readonly receivedCents: CodecTypes['pg/int4@1']['output'];
      readonly approvedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Sale: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly saleNumber: CodecTypes['pg/text@1']['output'];
      readonly storeCode: CodecTypes['pg/text@1']['output'];
      readonly registerCode: CodecTypes['pg/text@1']['output'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly totalCents: CodecTypes['pg/int4@1']['output'];
      readonly taxCents: CodecTypes['pg/int4@1']['output'];
      readonly netCents: CodecTypes['pg/int4@1']['output'];
      readonly costStatus: 'PENDING' | 'COSTED';
      readonly costCents: CodecTypes['pg/int4@1']['output'] | null;
      readonly costAttempts: CodecTypes['pg/int4@1']['output'];
      readonly lastCostError: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly SaleProduct: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly saleId: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly sku: CodecTypes['pg/text@1']['output'];
      readonly productName: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly revenueCents: CodecTypes['pg/int4@1']['output'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['output'] | null;
      readonly costCents: CodecTypes['pg/int4@1']['output'] | null;
      readonly storeCode: CodecTypes['pg/text@1']['output'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly SupplierBill: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['output'];
      readonly supplierId: CodecTypes['pg/text@1']['output'] | null;
      readonly supplierName: CodecTypes['pg/text@1']['output'] | null;
      readonly paymentTerms: CodecTypes['pg/text@1']['output'] | null;
      readonly dueDate: CodecTypes['pg/text@1']['output'] | null;
      readonly amountCents: CodecTypes['pg/int4@1']['output'];
      readonly paidCents: CodecTypes['pg/int4@1']['output'];
      readonly status: 'OPEN' | 'PAID';
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly SupplierPayment: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly supplierBillId: CodecTypes['pg/text@1']['output'];
      readonly journalEntryId: CodecTypes['pg/text@1']['output'];
      readonly amountCents: CodecTypes['pg/int4@1']['output'];
      readonly reference: CodecTypes['pg/text@1']['output'] | null;
      readonly paidAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly paidBy: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly JournalEntry: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly source: 'GOODS_RECEIVED' | 'SALE' | 'SALE_COST' | 'DAY_CLOSED' | 'SUPPLIER_PAYMENT';
      readonly reference: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly storeCode: CodecTypes['pg/text@1']['input'] | null;
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly JournalLine: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly journalEntryId: CodecTypes['pg/text@1']['input'];
      readonly accountCode: CodecTypes['pg/text@1']['input'];
      readonly debitCents: CodecTypes['pg/int4@1']['input'];
      readonly creditCents: CodecTypes['pg/int4@1']['input'];
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ProcessedEvent: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly PurchaseCommitment: {
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['input'];
      readonly supplierId: CodecTypes['pg/text@1']['input'];
      readonly supplierName: CodecTypes['pg/text@1']['input'];
      readonly paymentTerms: CodecTypes['pg/text@1']['input'];
      readonly totalCents: CodecTypes['pg/int4@1']['input'];
      readonly receivedCents: CodecTypes['pg/int4@1']['input'];
      readonly approvedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Sale: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly saleNumber: CodecTypes['pg/text@1']['input'];
      readonly storeCode: CodecTypes['pg/text@1']['input'];
      readonly registerCode: CodecTypes['pg/text@1']['input'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly totalCents: CodecTypes['pg/int4@1']['input'];
      readonly taxCents: CodecTypes['pg/int4@1']['input'];
      readonly netCents: CodecTypes['pg/int4@1']['input'];
      readonly costStatus: 'PENDING' | 'COSTED';
      readonly costCents: CodecTypes['pg/int4@1']['input'] | null;
      readonly costAttempts: CodecTypes['pg/int4@1']['input'];
      readonly lastCostError: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly SaleProduct: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly saleId: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly sku: CodecTypes['pg/text@1']['input'];
      readonly productName: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly revenueCents: CodecTypes['pg/int4@1']['input'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['input'] | null;
      readonly costCents: CodecTypes['pg/int4@1']['input'] | null;
      readonly storeCode: CodecTypes['pg/text@1']['input'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly SupplierBill: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['input'];
      readonly supplierId: CodecTypes['pg/text@1']['input'] | null;
      readonly supplierName: CodecTypes['pg/text@1']['input'] | null;
      readonly paymentTerms: CodecTypes['pg/text@1']['input'] | null;
      readonly dueDate: CodecTypes['pg/text@1']['input'] | null;
      readonly amountCents: CodecTypes['pg/int4@1']['input'];
      readonly paidCents: CodecTypes['pg/int4@1']['input'];
      readonly status: 'OPEN' | 'PAID';
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly SupplierPayment: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly supplierBillId: CodecTypes['pg/text@1']['input'];
      readonly journalEntryId: CodecTypes['pg/text@1']['input'];
      readonly amountCents: CodecTypes['pg/int4@1']['input'];
      readonly reference: CodecTypes['pg/text@1']['input'] | null;
      readonly paidAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly paidBy: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly journalEntry: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly reference: CodecTypes['pg/text@1']['output'];
      readonly source: 'GOODS_RECEIVED' | 'SALE' | 'SALE_COST' | 'DAY_CLOSED' | 'SUPPLIER_PAYMENT';
      readonly storeCode: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly journalLine: {
      readonly accountCode: CodecTypes['pg/text@1']['output'];
      readonly creditCents: CodecTypes['pg/int4@1']['output'];
      readonly debitCents: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly journalEntryId: CodecTypes['pg/text@1']['output'];
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly processedEvent: {
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
    };
    readonly purchaseCommitment: {
      readonly approvedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly paymentTerms: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['output'];
      readonly receivedCents: CodecTypes['pg/int4@1']['output'];
      readonly supplierId: CodecTypes['pg/text@1']['output'];
      readonly supplierName: CodecTypes['pg/text@1']['output'];
      readonly totalCents: CodecTypes['pg/int4@1']['output'];
    };
    readonly sale: {
      readonly costAttempts: CodecTypes['pg/int4@1']['output'];
      readonly costCents: CodecTypes['pg/int4@1']['output'] | null;
      readonly costStatus: 'PENDING' | 'COSTED';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lastCostError: CodecTypes['pg/text@1']['output'] | null;
      readonly netCents: CodecTypes['pg/int4@1']['output'];
      readonly registerCode: CodecTypes['pg/text@1']['output'];
      readonly saleNumber: CodecTypes['pg/text@1']['output'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly storeCode: CodecTypes['pg/text@1']['output'];
      readonly taxCents: CodecTypes['pg/int4@1']['output'];
      readonly totalCents: CodecTypes['pg/int4@1']['output'];
    };
    readonly saleProduct: {
      readonly costCents: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly productName: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly revenueCents: CodecTypes['pg/int4@1']['output'];
      readonly saleId: CodecTypes['pg/text@1']['output'];
      readonly sku: CodecTypes['pg/text@1']['output'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly storeCode: CodecTypes['pg/text@1']['output'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly supplierBill: {
      readonly amountCents: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly dueDate: CodecTypes['pg/text@1']['output'] | null;
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly paidCents: CodecTypes['pg/int4@1']['output'];
      readonly paymentTerms: CodecTypes['pg/text@1']['output'] | null;
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['output'];
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly status: 'OPEN' | 'PAID';
      readonly supplierId: CodecTypes['pg/text@1']['output'] | null;
      readonly supplierName: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly supplierPayment: {
      readonly amountCents: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly journalEntryId: CodecTypes['pg/text@1']['output'];
      readonly paidAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly paidBy: CodecTypes['pg/text@1']['output'];
      readonly reference: CodecTypes['pg/text@1']['output'] | null;
      readonly supplierBillId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly journalEntry: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly reference: CodecTypes['pg/text@1']['input'];
      readonly source: 'GOODS_RECEIVED' | 'SALE' | 'SALE_COST' | 'DAY_CLOSED' | 'SUPPLIER_PAYMENT';
      readonly storeCode: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly journalLine: {
      readonly accountCode: CodecTypes['pg/text@1']['input'];
      readonly creditCents: CodecTypes['pg/int4@1']['input'];
      readonly debitCents: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly journalEntryId: CodecTypes['pg/text@1']['input'];
      readonly occurredAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly processedEvent: {
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
    };
    readonly purchaseCommitment: {
      readonly approvedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly paymentTerms: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['input'];
      readonly receivedCents: CodecTypes['pg/int4@1']['input'];
      readonly supplierId: CodecTypes['pg/text@1']['input'];
      readonly supplierName: CodecTypes['pg/text@1']['input'];
      readonly totalCents: CodecTypes['pg/int4@1']['input'];
    };
    readonly sale: {
      readonly costAttempts: CodecTypes['pg/int4@1']['input'];
      readonly costCents: CodecTypes['pg/int4@1']['input'] | null;
      readonly costStatus: 'PENDING' | 'COSTED';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lastCostError: CodecTypes['pg/text@1']['input'] | null;
      readonly netCents: CodecTypes['pg/int4@1']['input'];
      readonly registerCode: CodecTypes['pg/text@1']['input'];
      readonly saleNumber: CodecTypes['pg/text@1']['input'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly storeCode: CodecTypes['pg/text@1']['input'];
      readonly taxCents: CodecTypes['pg/int4@1']['input'];
      readonly totalCents: CodecTypes['pg/int4@1']['input'];
    };
    readonly saleProduct: {
      readonly costCents: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly productName: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly revenueCents: CodecTypes['pg/int4@1']['input'];
      readonly saleId: CodecTypes['pg/text@1']['input'];
      readonly sku: CodecTypes['pg/text@1']['input'];
      readonly soldAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly storeCode: CodecTypes['pg/text@1']['input'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly supplierBill: {
      readonly amountCents: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly dueDate: CodecTypes['pg/text@1']['input'] | null;
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly paidCents: CodecTypes['pg/int4@1']['input'];
      readonly paymentTerms: CodecTypes['pg/text@1']['input'] | null;
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderNumber: CodecTypes['pg/text@1']['input'];
      readonly receivedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly status: 'OPEN' | 'PAID';
      readonly supplierId: CodecTypes['pg/text@1']['input'] | null;
      readonly supplierName: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly supplierPayment: {
      readonly amountCents: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly journalEntryId: CodecTypes['pg/text@1']['input'];
      readonly paidAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly paidBy: CodecTypes['pg/text@1']['input'];
      readonly reference: CodecTypes['pg/text@1']['input'] | null;
      readonly supplierBillId: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly journalEntry: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly reference: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly storeCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly occurredAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'journalEntry_occurredAt_idx_c6b89167';
                  readonly prefix: 'journalEntry_occurredAt_idx';
                  readonly columns: readonly ['occurredAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'journalEntry_source_idx_c937a07d';
                  readonly prefix: 'journalEntry_source_idx';
                  readonly columns: readonly ['source'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly journalLine: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly journalEntryId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly accountCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly debitCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly creditCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly occurredAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'journalLine_accountCode_occurredAt_idx_505ed1fa';
                  readonly prefix: 'journalLine_accountCode_occurredAt_idx';
                  readonly columns: readonly ['accountCode', 'occurredAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'journalLine_journalEntryId_idx_9f65b209';
                  readonly prefix: 'journalLine_journalEntryId_idx';
                  readonly columns: readonly ['journalEntryId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'journalLine';
                    readonly columns: readonly ['journalEntryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'journalEntry';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly processedEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly eventType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly handledAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly purchaseCommitment: {
              columns: {
                readonly purchaseOrderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly purchaseOrderNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly paymentTerms: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly totalCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly receivedCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly approvedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['purchaseOrderId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly sale: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly saleNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly storeCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly registerCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly soldAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly totalCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly taxCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly netCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly costStatus: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly costCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly costAttempts: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly lastCostError: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['saleNumber'] }];
              indexes: readonly [
                {
                  readonly name: 'sale_costStatus_idx_223aba25';
                  readonly prefix: 'sale_costStatus_idx';
                  readonly columns: readonly ['costStatus'];
                  readonly unique: false;
                },
                {
                  readonly name: 'sale_soldAt_idx_a04fbeab';
                  readonly prefix: 'sale_soldAt_idx';
                  readonly columns: readonly ['soldAt'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly saleProduct: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly saleId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sku: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly revenueCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly unitCostCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly costCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly storeCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly soldAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'saleProduct_sku_idx_506e4b93';
                  readonly prefix: 'saleProduct_sku_idx';
                  readonly columns: readonly ['sku'];
                  readonly unique: false;
                },
                {
                  readonly name: 'saleProduct_storeCode_soldAt_idx_8e178b83';
                  readonly prefix: 'saleProduct_storeCode_soldAt_idx';
                  readonly columns: readonly ['storeCode', 'soldAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'saleProduct_saleId_idx_b4c0fb73';
                  readonly prefix: 'saleProduct_saleId_idx';
                  readonly columns: readonly ['saleId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'saleProduct';
                    readonly columns: readonly ['saleId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sale';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly supplierBill: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly goodsReceivedNoteNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly purchaseOrderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly purchaseOrderNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly supplierName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly paymentTerms: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly dueDate: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly amountCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly paidCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPEN'>;
                  };
                };
                readonly receivedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['goodsReceivedNoteNumber'] }];
              indexes: readonly [
                {
                  readonly name: 'supplierBill_status_dueDate_idx_ec56e113';
                  readonly prefix: 'supplierBill_status_dueDate_idx';
                  readonly columns: readonly ['status', 'dueDate'];
                  readonly unique: false;
                },
                {
                  readonly name: 'supplierBill_supplierId_idx_c4d9a8b9';
                  readonly prefix: 'supplierBill_supplierId_idx';
                  readonly columns: readonly ['supplierId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'supplierBill_purchaseOrderId_idx_3e3a8c45';
                  readonly prefix: 'supplierBill_purchaseOrderId_idx';
                  readonly columns: readonly ['purchaseOrderId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly supplierPayment: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierBillId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly journalEntryId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly amountCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reference: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly paidAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly paidBy: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'supplierPayment_supplierBillId_idx_f6888116';
                  readonly prefix: 'supplierPayment_supplierBillId_idx';
                  readonly columns: readonly ['supplierBillId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'supplierPayment';
                    readonly columns: readonly ['supplierBillId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'supplierBill';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly BillStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['OPEN', 'PAID'];
            };
            readonly CostStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'COSTED'];
            };
            readonly JournalSource: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'GOODS_RECEIVED',
                'SALE',
                'SALE_COST',
                'DAY_CLOSED',
                'SUPPLIER_PAYMENT',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly journalEntry: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'JournalEntry';
    };
    readonly journalLine: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'JournalLine';
    };
    readonly purchaseCommitment: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PurchaseCommitment';
    };
    readonly supplierBill: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SupplierBill';
    };
    readonly supplierPayment: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SupplierPayment';
    };
    readonly sale: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sale' };
    readonly saleProduct: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SaleProduct';
    };
    readonly processedEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProcessedEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly JournalEntry: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reference: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly storeCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly occurredAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly lines: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JournalLine';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['journalEntryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'journalEntry';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly source: { readonly column: 'source' };
                readonly reference: { readonly column: 'reference' };
                readonly description: { readonly column: 'description' };
                readonly storeCode: { readonly column: 'storeCode' };
                readonly occurredAt: { readonly column: 'occurredAt' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly JournalLine: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly journalEntryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accountCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly debitCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly creditCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly occurredAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly entry: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'JournalEntry';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['journalEntryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'journalLine';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly journalEntryId: { readonly column: 'journalEntryId' };
                readonly accountCode: { readonly column: 'accountCode' };
                readonly debitCents: { readonly column: 'debitCents' };
                readonly creditCents: { readonly column: 'creditCents' };
                readonly occurredAt: { readonly column: 'occurredAt' };
              };
            };
          };
          readonly ProcessedEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly handledAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'processedEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly eventType: { readonly column: 'eventType' };
                readonly handledAt: { readonly column: 'handledAt' };
              };
            };
          };
          readonly PurchaseCommitment: {
            readonly fields: {
              readonly purchaseOrderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purchaseOrderNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentTerms: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly totalCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly receivedCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly approvedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'purchaseCommitment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly purchaseOrderId: { readonly column: 'purchaseOrderId' };
                readonly purchaseOrderNumber: { readonly column: 'purchaseOrderNumber' };
                readonly supplierId: { readonly column: 'supplierId' };
                readonly supplierName: { readonly column: 'supplierName' };
                readonly paymentTerms: { readonly column: 'paymentTerms' };
                readonly totalCents: { readonly column: 'totalCents' };
                readonly receivedCents: { readonly column: 'receivedCents' };
                readonly approvedAt: { readonly column: 'approvedAt' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Sale: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly saleNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly storeCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly registerCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly soldAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly totalCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly taxCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly netCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly costStatus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly costCents: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly costAttempts: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly lastCostError: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SaleProduct';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['saleId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'sale';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly saleNumber: { readonly column: 'saleNumber' };
                readonly storeCode: { readonly column: 'storeCode' };
                readonly registerCode: { readonly column: 'registerCode' };
                readonly soldAt: { readonly column: 'soldAt' };
                readonly totalCents: { readonly column: 'totalCents' };
                readonly taxCents: { readonly column: 'taxCents' };
                readonly netCents: { readonly column: 'netCents' };
                readonly costStatus: { readonly column: 'costStatus' };
                readonly costCents: { readonly column: 'costCents' };
                readonly costAttempts: { readonly column: 'costAttempts' };
                readonly lastCostError: { readonly column: 'lastCostError' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly SaleProduct: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly saleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sku: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly revenueCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unitCostCents: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly costCents: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly storeCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly soldAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly sale: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Sale' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['saleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'saleProduct';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly saleId: { readonly column: 'saleId' };
                readonly productId: { readonly column: 'productId' };
                readonly sku: { readonly column: 'sku' };
                readonly productName: { readonly column: 'productName' };
                readonly quantity: { readonly column: 'quantity' };
                readonly revenueCents: { readonly column: 'revenueCents' };
                readonly unitCostCents: { readonly column: 'unitCostCents' };
                readonly costCents: { readonly column: 'costCents' };
                readonly storeCode: { readonly column: 'storeCode' };
                readonly soldAt: { readonly column: 'soldAt' };
              };
            };
          };
          readonly SupplierBill: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly goodsReceivedNoteNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purchaseOrderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purchaseOrderNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentTerms: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dueDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly amountCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly paidCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly receivedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly payments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SupplierPayment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['supplierBillId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'supplierBill';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly goodsReceivedNoteNumber: { readonly column: 'goodsReceivedNoteNumber' };
                readonly purchaseOrderId: { readonly column: 'purchaseOrderId' };
                readonly purchaseOrderNumber: { readonly column: 'purchaseOrderNumber' };
                readonly supplierId: { readonly column: 'supplierId' };
                readonly supplierName: { readonly column: 'supplierName' };
                readonly paymentTerms: { readonly column: 'paymentTerms' };
                readonly dueDate: { readonly column: 'dueDate' };
                readonly amountCents: { readonly column: 'amountCents' };
                readonly paidCents: { readonly column: 'paidCents' };
                readonly status: { readonly column: 'status' };
                readonly receivedAt: { readonly column: 'receivedAt' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly SupplierPayment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierBillId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly journalEntryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly amountCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reference: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paidAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly paidBy: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly bill: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SupplierBill';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['supplierBillId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'supplierPayment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly supplierBillId: { readonly column: 'supplierBillId' };
                readonly journalEntryId: { readonly column: 'journalEntryId' };
                readonly amountCents: { readonly column: 'amountCents' };
                readonly reference: { readonly column: 'reference' };
                readonly paidAt: { readonly column: 'paidAt' };
                readonly paidBy: { readonly column: 'paidBy' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly JournalSource: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'GOODS_RECEIVED'; readonly value: 'GOODS_RECEIVED' },
              { readonly name: 'SALE'; readonly value: 'SALE' },
              { readonly name: 'SALE_COST'; readonly value: 'SALE_COST' },
              { readonly name: 'DAY_CLOSED'; readonly value: 'DAY_CLOSED' },
              { readonly name: 'SUPPLIER_PAYMENT'; readonly value: 'SUPPLIER_PAYMENT' },
            ];
          };
          readonly BillStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'OPEN'; readonly value: 'OPEN' },
              { readonly name: 'PAID'; readonly value: 'PAID' },
            ];
          };
          readonly CostStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'COSTED'; readonly value: 'COSTED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'journalEntry';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'journalLine';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'sale';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'saleProduct';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'supplierBill';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'supplierBill';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'supplierPayment';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
