// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'bfc1f324952bc169e64b3f044e35af3262ddaa7b2b43313f67b85d2450e726a9'>;
export type ExecutionHash =
  ExecutionHashBase<'fbef2618107ff640f83a48ff4358604131159778ee44d2b723a59dfee215b567'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly ExpectedDelivery: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly poNumber: CodecTypes['pg/text@1']['output'];
      readonly supplierId: CodecTypes['pg/text@1']['output'];
      readonly supplierName: CodecTypes['pg/text@1']['output'];
      readonly status: 'OPEN' | 'CLOSED';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ExpectedProduct: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly productName: CodecTypes['pg/text@1']['output'];
      readonly quantityOrdered: CodecTypes['pg/int4@1']['output'];
      readonly quantityReceived: CodecTypes['pg/int4@1']['output'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['output'];
    };
    readonly GoodsReceivedNote: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['output'];
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly poNumber: CodecTypes['pg/text@1']['output'];
      readonly supplierId: CodecTypes['pg/text@1']['output'];
      readonly locationCode: CodecTypes['pg/text@1']['output'];
      readonly receivedBy: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly GoodsReceivedNoteProduct: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly goodsReceivedNoteId: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly productName: CodecTypes['pg/text@1']['output'];
      readonly quantityExpected: CodecTypes['pg/int4@1']['output'];
      readonly quantityDelivered: CodecTypes['pg/int4@1']['output'];
      readonly quantityDamaged: CodecTypes['pg/int4@1']['output'];
      readonly quantityAccepted: CodecTypes['pg/int4@1']['output'];
      readonly discrepancy: 'NONE' | 'LESS' | 'MORE' | 'NOT_ORDERED';
      readonly unitCostCents: CodecTypes['pg/int4@1']['output'];
    };
    readonly OutboxEvent: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly aggregateId: CodecTypes['pg/text@1']['output'];
      readonly payload: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'PUBLISHED' | 'DEAD';
      readonly publishedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly attempts: CodecTypes['pg/int4@1']['output'];
      readonly lastError: CodecTypes['pg/text@1']['output'] | null;
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deadAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ProcessedEvent: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly ExpectedDelivery: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly poNumber: CodecTypes['pg/text@1']['input'];
      readonly supplierId: CodecTypes['pg/text@1']['input'];
      readonly supplierName: CodecTypes['pg/text@1']['input'];
      readonly status: 'OPEN' | 'CLOSED';
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ExpectedProduct: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly productName: CodecTypes['pg/text@1']['input'];
      readonly quantityOrdered: CodecTypes['pg/int4@1']['input'];
      readonly quantityReceived: CodecTypes['pg/int4@1']['input'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['input'];
    };
    readonly GoodsReceivedNote: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['input'];
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly poNumber: CodecTypes['pg/text@1']['input'];
      readonly supplierId: CodecTypes['pg/text@1']['input'];
      readonly locationCode: CodecTypes['pg/text@1']['input'];
      readonly receivedBy: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly GoodsReceivedNoteProduct: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly goodsReceivedNoteId: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly productName: CodecTypes['pg/text@1']['input'];
      readonly quantityExpected: CodecTypes['pg/int4@1']['input'];
      readonly quantityDelivered: CodecTypes['pg/int4@1']['input'];
      readonly quantityDamaged: CodecTypes['pg/int4@1']['input'];
      readonly quantityAccepted: CodecTypes['pg/int4@1']['input'];
      readonly discrepancy: 'NONE' | 'LESS' | 'MORE' | 'NOT_ORDERED';
      readonly unitCostCents: CodecTypes['pg/int4@1']['input'];
    };
    readonly OutboxEvent: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly aggregateId: CodecTypes['pg/text@1']['input'];
      readonly payload: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'PUBLISHED' | 'DEAD';
      readonly publishedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly attempts: CodecTypes['pg/int4@1']['input'];
      readonly lastError: CodecTypes['pg/text@1']['input'] | null;
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deadAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ProcessedEvent: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly expectedDelivery: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly poNumber: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly status: 'OPEN' | 'CLOSED';
      readonly supplierId: CodecTypes['pg/text@1']['output'];
      readonly supplierName: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly expectedProduct: {
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly productName: CodecTypes['pg/text@1']['output'];
      readonly quantityOrdered: CodecTypes['pg/int4@1']['output'];
      readonly quantityReceived: CodecTypes['pg/int4@1']['output'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['output'];
    };
    readonly goodsReceivedNote: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['output'];
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly locationCode: CodecTypes['pg/text@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly poNumber: CodecTypes['pg/text@1']['output'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['output'];
      readonly receivedBy: CodecTypes['pg/text@1']['output'];
      readonly supplierId: CodecTypes['pg/text@1']['output'];
    };
    readonly goodsReceivedNoteProduct: {
      readonly discrepancy: 'NONE' | 'LESS' | 'MORE' | 'NOT_ORDERED';
      readonly goodsReceivedNoteId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly productId: CodecTypes['pg/text@1']['output'];
      readonly productName: CodecTypes['pg/text@1']['output'];
      readonly quantityAccepted: CodecTypes['pg/int4@1']['output'];
      readonly quantityDamaged: CodecTypes['pg/int4@1']['output'];
      readonly quantityDelivered: CodecTypes['pg/int4@1']['output'];
      readonly quantityExpected: CodecTypes['pg/int4@1']['output'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['output'];
    };
    readonly outboxEvent: {
      readonly aggregateId: CodecTypes['pg/text@1']['output'];
      readonly attempts: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly deadAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lastError: CodecTypes['pg/text@1']['output'] | null;
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly payload: CodecTypes['pg/text@1']['output'];
      readonly publishedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly status: 'PENDING' | 'PUBLISHED' | 'DEAD';
    };
    readonly processedEvent: {
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly expectedDelivery: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly poNumber: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly status: 'OPEN' | 'CLOSED';
      readonly supplierId: CodecTypes['pg/text@1']['input'];
      readonly supplierName: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly expectedProduct: {
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly productName: CodecTypes['pg/text@1']['input'];
      readonly quantityOrdered: CodecTypes['pg/int4@1']['input'];
      readonly quantityReceived: CodecTypes['pg/int4@1']['input'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['input'];
    };
    readonly goodsReceivedNote: {
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expectedDeliveryId: CodecTypes['pg/text@1']['input'];
      readonly goodsReceivedNoteNumber: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly locationCode: CodecTypes['pg/text@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly poNumber: CodecTypes['pg/text@1']['input'];
      readonly purchaseOrderId: CodecTypes['pg/text@1']['input'];
      readonly receivedBy: CodecTypes['pg/text@1']['input'];
      readonly supplierId: CodecTypes['pg/text@1']['input'];
    };
    readonly goodsReceivedNoteProduct: {
      readonly discrepancy: 'NONE' | 'LESS' | 'MORE' | 'NOT_ORDERED';
      readonly goodsReceivedNoteId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly productId: CodecTypes['pg/text@1']['input'];
      readonly productName: CodecTypes['pg/text@1']['input'];
      readonly quantityAccepted: CodecTypes['pg/int4@1']['input'];
      readonly quantityDamaged: CodecTypes['pg/int4@1']['input'];
      readonly quantityDelivered: CodecTypes['pg/int4@1']['input'];
      readonly quantityExpected: CodecTypes['pg/int4@1']['input'];
      readonly unitCostCents: CodecTypes['pg/int4@1']['input'];
    };
    readonly outboxEvent: {
      readonly aggregateId: CodecTypes['pg/text@1']['input'];
      readonly attempts: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly deadAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lastError: CodecTypes['pg/text@1']['input'] | null;
      readonly nextAttemptAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly payload: CodecTypes['pg/text@1']['input'];
      readonly publishedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly status: 'PENDING' | 'PUBLISHED' | 'DEAD';
    };
    readonly processedEvent: {
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly handledAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly expectedDelivery: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly purchaseOrderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly poNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'OPEN'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['purchaseOrderId'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly expectedProduct: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly expectedDeliveryId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantityOrdered: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantityReceived: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly unitCostCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['expectedDeliveryId', 'productId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'expectedProduct_expectedDeliveryId_idx_f6880cbc';
                  readonly prefix: 'expectedProduct_expectedDeliveryId_idx';
                  readonly columns: readonly ['expectedDeliveryId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'expectedProduct';
                    readonly columns: readonly ['expectedDeliveryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'expectedDelivery';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly goodsReceivedNote: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly goodsReceivedNoteNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly expectedDeliveryId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly purchaseOrderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly poNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly supplierId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly locationCode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly receivedBy: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['goodsReceivedNoteNumber'] }];
              indexes: readonly [
                {
                  readonly name: 'goodsReceivedNote_expectedDeliveryId_idx_f6880cbc';
                  readonly prefix: 'goodsReceivedNote_expectedDeliveryId_idx';
                  readonly columns: readonly ['expectedDeliveryId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'goodsReceivedNote';
                    readonly columns: readonly ['expectedDeliveryId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'expectedDelivery';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly goodsReceivedNoteProduct: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly goodsReceivedNoteId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly productName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantityExpected: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantityDelivered: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantityDamaged: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly quantityAccepted: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly discrepancy: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly unitCostCents: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'goodsReceivedNoteProduct_goodsReceivedNoteId_idx_05284e9f';
                  readonly prefix: 'goodsReceivedNoteProduct_goodsReceivedNoteId_idx';
                  readonly columns: readonly ['goodsReceivedNoteId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'goodsReceivedNoteProduct';
                    readonly columns: readonly ['goodsReceivedNoteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'goodsReceivedNote';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly outboxEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly eventType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly aggregateId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly publishedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly attempts: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly lastError: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly nextAttemptAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly deadAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'outboxEvent_status_nextAttemptAt_idx_8ba20615';
                  readonly prefix: 'outboxEvent_status_nextAttemptAt_idx';
                  readonly columns: readonly ['status', 'nextAttemptAt'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly processedEvent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly eventType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly handledAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Discrepancy: {
              readonly kind: 'valueSet';
              readonly values: readonly ['NONE', 'LESS', 'MORE', 'NOT_ORDERED'];
            };
            readonly ExpectedDeliveryStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['OPEN', 'CLOSED'];
            };
            readonly OutboxEventStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'PUBLISHED', 'DEAD'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly expectedDelivery: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ExpectedDelivery';
    };
    readonly expectedProduct: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ExpectedProduct';
    };
    readonly goodsReceivedNote: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'GoodsReceivedNote';
    };
    readonly goodsReceivedNoteProduct: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'GoodsReceivedNoteProduct';
    };
    readonly outboxEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OutboxEvent';
    };
    readonly processedEvent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProcessedEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly ExpectedDelivery: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purchaseOrderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly poNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly goodsReceivedNotes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GoodsReceivedNote';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['expectedDeliveryId'];
                };
              };
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExpectedProduct';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['expectedDeliveryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'expectedDelivery';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly purchaseOrderId: { readonly column: 'purchaseOrderId' };
                readonly poNumber: { readonly column: 'poNumber' };
                readonly supplierId: { readonly column: 'supplierId' };
                readonly supplierName: { readonly column: 'supplierName' };
                readonly status: { readonly column: 'status' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly ExpectedProduct: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expectedDeliveryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantityOrdered: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantityReceived: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unitCostCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly expectedDelivery: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExpectedDelivery';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['expectedDeliveryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'expectedProduct';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly expectedDeliveryId: { readonly column: 'expectedDeliveryId' };
                readonly productId: { readonly column: 'productId' };
                readonly productName: { readonly column: 'productName' };
                readonly quantityOrdered: { readonly column: 'quantityOrdered' };
                readonly quantityReceived: { readonly column: 'quantityReceived' };
                readonly unitCostCents: { readonly column: 'unitCostCents' };
              };
            };
          };
          readonly GoodsReceivedNote: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly goodsReceivedNoteNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expectedDeliveryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly purchaseOrderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly poNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly supplierId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly locationCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly receivedBy: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly expectedDelivery: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExpectedDelivery';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['expectedDeliveryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly products: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GoodsReceivedNoteProduct';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['goodsReceivedNoteId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'goodsReceivedNote';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly goodsReceivedNoteNumber: { readonly column: 'goodsReceivedNoteNumber' };
                readonly expectedDeliveryId: { readonly column: 'expectedDeliveryId' };
                readonly purchaseOrderId: { readonly column: 'purchaseOrderId' };
                readonly poNumber: { readonly column: 'poNumber' };
                readonly supplierId: { readonly column: 'supplierId' };
                readonly locationCode: { readonly column: 'locationCode' };
                readonly receivedBy: { readonly column: 'receivedBy' };
                readonly notes: { readonly column: 'notes' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly GoodsReceivedNoteProduct: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly goodsReceivedNoteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantityExpected: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantityDelivered: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantityDamaged: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantityAccepted: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly discrepancy: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly unitCostCents: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly goodsReceivedNote: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GoodsReceivedNote';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['goodsReceivedNoteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'goodsReceivedNoteProduct';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly goodsReceivedNoteId: { readonly column: 'goodsReceivedNoteId' };
                readonly productId: { readonly column: 'productId' };
                readonly productName: { readonly column: 'productName' };
                readonly quantityExpected: { readonly column: 'quantityExpected' };
                readonly quantityDelivered: { readonly column: 'quantityDelivered' };
                readonly quantityDamaged: { readonly column: 'quantityDamaged' };
                readonly quantityAccepted: { readonly column: 'quantityAccepted' };
                readonly discrepancy: { readonly column: 'discrepancy' };
                readonly unitCostCents: { readonly column: 'unitCostCents' };
              };
            };
          };
          readonly OutboxEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly aggregateId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly publishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly attempts: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly lastError: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nextAttemptAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly deadAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'outboxEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly eventType: { readonly column: 'eventType' };
                readonly aggregateId: { readonly column: 'aggregateId' };
                readonly payload: { readonly column: 'payload' };
                readonly status: { readonly column: 'status' };
                readonly publishedAt: { readonly column: 'publishedAt' };
                readonly attempts: { readonly column: 'attempts' };
                readonly lastError: { readonly column: 'lastError' };
                readonly nextAttemptAt: { readonly column: 'nextAttemptAt' };
                readonly deadAt: { readonly column: 'deadAt' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly ProcessedEvent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly eventType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly handledAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'processedEvent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly eventType: { readonly column: 'eventType' };
                readonly handledAt: { readonly column: 'handledAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly ExpectedDeliveryStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'OPEN'; readonly value: 'OPEN' },
              { readonly name: 'CLOSED'; readonly value: 'CLOSED' },
            ];
          };
          readonly Discrepancy: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NONE'; readonly value: 'NONE' },
              { readonly name: 'LESS'; readonly value: 'LESS' },
              { readonly name: 'MORE'; readonly value: 'MORE' },
              { readonly name: 'NOT_ORDERED'; readonly value: 'NOT_ORDERED' },
            ];
          };
          readonly OutboxEventStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PUBLISHED'; readonly value: 'PUBLISHED' },
              { readonly name: 'DEAD'; readonly value: 'DEAD' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'expectedDelivery';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'expectedDelivery';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'expectedProduct';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'goodsReceivedNote';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'goodsReceivedNoteProduct';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'outboxEvent';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
